version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  micro1:
    build: ./task_API
    ports:
      - "8000:8000"
    volumes:
      - ./task_API:/app
      - task_API_db:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/test.db

  micro2:
    build: ./Celery_task
    depends_on:
      - redis
      - task_API
    volumes:
      - ./Celery_task:/app
      - task_API_db:/app/../task_API  # Общий доступ к БД первого микросервиса
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:////app/../task_API/test.db

volumes:
  redis_data:
  task_API_db: